source 'http://rubygems.org'

gem 'sinatra', '1.4.8'
gem 'haml', '4.0.7'
gem 'pocket-ruby'
gem 'json'
gem 'watir', '5.0.0'
gem 'watir-webdriver', '0.9.1'
gem 'thor'
gem 'activerecord', '5.0.2'
gem 'sqlite3'
gem 'clockwork'
