default: &default
  adapter: sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: development.sqlite3


production:
  <<: *default
  database: production.sqlite3